# Copyright and license information

copyright_image:
copyright_image_link:
copyright_text: 'Except where otherwise noted, content on this site is licensed under the Creative Commons Attribution License (CC-BY). Images are by default open-access under the terms of the CC BY-NC-SA license, unless stated otherwise.'
