---
# Navigation header configuration

header_logo_url: /images/header-logo-tubifer.png?v=cut-flip
header_logo_text: 'Ceraphronoidea of the World'
header_links:
  - label: Home
    link: /

  - label: Search DwC
    link: /resources/tw/filter/dwc_otus

  - label: Bibliography
    link: /resources/tw/filter/bibliography

  - label: Keys
    link: /keys

  - label: About
    link: /about
