# Project metadata

project_name: Ceraphronoidea of the World
project_citation: Ceraphronoidea of the World. Taxon pages served from TaxonWorks.
project_url: https://shanetiltongc.github.io/Ceraphronoidea-of-the-World/
project_authors:
